/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  UserInterest as PrismaUserInterest,
  Event as PrismaEvent,
  Profile as PrismaProfile,
} from "@prisma/client";

export class UserInterestServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.UserInterestCountArgs, "select">
  ): Promise<number> {
    return this.prisma.userInterest.count(args);
  }

  async userInterests(
    args: Prisma.UserInterestFindManyArgs
  ): Promise<PrismaUserInterest[]> {
    return this.prisma.userInterest.findMany(args);
  }
  async userInterest(
    args: Prisma.UserInterestFindUniqueArgs
  ): Promise<PrismaUserInterest | null> {
    return this.prisma.userInterest.findUnique(args);
  }
  async createUserInterest(
    args: Prisma.UserInterestCreateArgs
  ): Promise<PrismaUserInterest> {
    return this.prisma.userInterest.create(args);
  }
  async updateUserInterest(
    args: Prisma.UserInterestUpdateArgs
  ): Promise<PrismaUserInterest> {
    return this.prisma.userInterest.update(args);
  }
  async deleteUserInterest(
    args: Prisma.UserInterestDeleteArgs
  ): Promise<PrismaUserInterest> {
    return this.prisma.userInterest.delete(args);
  }

  async getEvent(parentId: string): Promise<PrismaEvent | null> {
    return this.prisma.userInterest
      .findUnique({
        where: { id: parentId },
      })
      .event();
  }

  async getProfile(parentId: string): Promise<PrismaProfile | null> {
    return this.prisma.userInterest
      .findUnique({
        where: { id: parentId },
      })
      .profile();
  }
}
