/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
  IsEnum,
} from "class-validator";
import { EventCreateNestedManyWithoutProfilesInput } from "./EventCreateNestedManyWithoutProfilesInput";
import { Type } from "class-transformer";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { EnumProfileProfileType } from "./EnumProfileProfileType";
import { UserInterestCreateNestedManyWithoutProfilesInput } from "./UserInterestCreateNestedManyWithoutProfilesInput";

@InputType()
class ProfileCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  bio?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: () => EventCreateNestedManyWithoutProfilesInput,
  })
  @ValidateNested()
  @Type(() => EventCreateNestedManyWithoutProfilesInput)
  @IsOptional()
  @Field(() => EventCreateNestedManyWithoutProfilesInput, {
    nullable: true,
  })
  events?: EventCreateNestedManyWithoutProfilesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  profilePicture?: InputJsonValue;

  @ApiProperty({
    required: false,
    enum: EnumProfileProfileType,
  })
  @IsEnum(EnumProfileProfileType)
  @IsOptional()
  @Field(() => EnumProfileProfileType, {
    nullable: true,
  })
  profileType?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: () => UserInterestCreateNestedManyWithoutProfilesInput,
  })
  @ValidateNested()
  @Type(() => UserInterestCreateNestedManyWithoutProfilesInput)
  @IsOptional()
  @Field(() => UserInterestCreateNestedManyWithoutProfilesInput, {
    nullable: true,
  })
  userInterests?: UserInterestCreateNestedManyWithoutProfilesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  websiteLink?: string | null;
}

export { ProfileCreateInput as ProfileCreateInput };
